# Site settings
title: Ricky Libunao &vert; Photographer &vert; Videographer &vert; Graphic Designer
email: rickyplibunao@gmail.com
url: rickylibunao.com
description: "I’m an experienced Photographer, Videographer, Graphic/Web
Designer seeking full-time position in the Field of social media,
marketing communications and other related-fields where I can
apply my skills for continuous improvement."
keywords: "Ricky Libunao, Photographer Bangkok, Graphic Design Bangkok"
skills: "Photographer - Videographer - Graphic Designer"
meta_author: Ricky Libunao

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18b #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Ricky Libunao
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: flickr
    url: https://www.flickr.com/people/rickylibunao
  - title: linkedin
    url: https://linkedin.com/in/rickylibunao
  - title: github
    url: https://github.com/rickylibunao

# Postal address (add as many lines as necessary)
address:
  - line: Bangkok, Thailand 10241

# Credits content
credits: '<a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer Theme</a>.'

# Build settings
markdown: kramdown
permalink: pretty
